language: node_js
node_js:
  - '10'
cache:
  directories:
    - node_modules
script:
  - npm run lint
  - npm run test
after_success:
  - npm run coveralls
  - cd website && npm install && npm run build
deploy:
  - provider: npm
    email: guilherme.albino.francisco@gmail.com
    api_key:
      secure: NLV5g0UCCDXDVP0wQjY9glubFfAvhPX7A1E7Lkv7k6u+b5ZuromB/E9Na82WWB/GX20gwHCEMB6kzqoG9FUvag6ZeXrVQFHrPlr3fFz4L2oAwhd9kcGe7IPfv9SN0eNH/NAYUQWzcSxukjqh/I95X+jPa6Fl7tgN9IwXYFIcXPsFfHj8+xJrsqGiFt77FB9QVfmZx/lCtq7tBu1b9Jo/6FwNK5BXWburW+JRF50FcppestFLA1mkiXPovPj6aTV1mXAQwMimE1jafU4vA/I7eZHglaVLav1YYsGeW6cpmMsYL4ecxFkRvqUjLAMstczAjNjJXTbvnEHVdq6YOfnBbZDAYbJ2r8COj4qCke52Xzrxl8SICmZJegos8Ty59WJfHsOJoNSgZMHIztQg2MUdTQp7T44tBtuNRCyo7qY3N6Z0+Up04aKnUp5nsiAhlllih6K7LZZb1c9MQ8s6ZTQ5ynpQJnu3Dfn4yMLQG61JGrKQvGZc/RJ7xLjYjkBiXtBV6bZphf86Tm1BY+vVdDYkgingYUQchaRjVik4W/MhO0F+a7AigDWO7J3SwSSROexMJCepdmTd6bvIt/6X4qof7l8SopFD3K4t7UgJ1GpnpvDkzBJvhqBqwjAwDhRPwqT82+srJhvQYKcv2IyvI8AyLL29D4pmV1pniIgk6cgMYXg=
    on:
      tags: true
  - provider: pages
    local-dir: ./docs/build/maslow
    skip-cleanup: true
    github-token:
      secure: MyglOGCskNdp6MwmURBodluyAsU+Rxxz7oMQUuIxjyR2CUy6NjuxIVQtTGOESv7yFDxtVr+kwW8M+KZGLCLOqJtIXHOILBG4NOeT31955e9r2FFL2MngKhtoZvuXrCnqqhuQZrmvQYdGXjLGHuNI32A2lv2yJ2AdhMNC+sOIKZrzJaHKCTG6YaAB0QI2K9lczkKbRwfkVVANU0gojJlfeoxrrZQDpNc1NJ1eJ19uxzW9TNjO48GRD3cSUpFI4/bTiw532H/vX1LiEMLnhRmi+GTRGTfSB0BGJmNQcHYvHN+poC+4GXL2HH+tgY0c9NvAXvrsr8FsXdcAUS46Y1Gbl0vTWgidPAE6F8QjA4QTm27RXONwwy9DJMieXkOckvtxg11+VCuY6czwTvgOoiIvI7bH1TVkNFDpyO1BAL9Pn70Z/yVskcue1umfu/IMF7Db0wpJUkPqEbgstruPHWlxJZ2uP3bgfMLf8w+ZwF/49q+yAG2eABDi1HCgNI5W802SUrEPd33L1+F1aTdIAWhiXjfiKdqwyVLxrzuCRNjnKTuOIl1WrHi1KBISOVhcNDj8QbDqOZuRKWX2YAHx5CH81yhD4/MJInPDU8cICDtAjfYX6nIdYR/RG/jDwr4KwY15qe6rEl+h3gfc07AuGx1AOtGps810BqFXJHgAMecRSbc=
    keep-history: true
    on:
      branch: master
  